// Movies
export const GET_ALL_MOVIES_REQUEST = 'movie/GET_ALL_MOVIES_REQUEST';
export const GET_ALL_MOVIES_SUCCESS = 'movie/GET_ALL_MOVIES_SUCCESS';
export const GET_ALL_MOVIES_FAILURE = 'movie/GET_ALL_MOVIES_FAILURE';
